version: "3.8"

services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      # Add your environment variables here
      - GOOGLE_VERTEX_PROJECT=${GOOGLE_VERTEX_PROJECT}
      - GOOGLE_VERTEX_LOCATION=${GOOGLE_VERTEX_LOCATION}
      - GOOGLE_VERTEX_CLIENT_EMAIL=${GOOGLE_VERTEX_CLIENT_EMAIL}
      - GOOGLE_VERTEX_PRIVATE_KEY=${GOOGLE_VERTEX_PRIVATE_KEY}
      - FAUST_SECRET_KEY=${FAUST_SECRET_KEY}
      - WORDPRESS_URL=${WORDPRESS_URL}
      - NEXT_PUBLIC_WORDPRESS_URL=${NEXT_PUBLIC_WORDPRESS_URL}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
